### ISSUE TITLE
Need help understanding the code

### ISSUE THREAD

**Issue by AnSem-Ellwood** [python-ivi/python-ivi#22]
I am trying to write a class for a TestEquity halfcube, which uses the same controller.  Since I have Python I dont need to write a profile. I just need one command: go_to_temperature which sets the temperature, asks the machine to go there and returns when the measured temperature is within half of a degree of the given temperature.  There does not seem to be any function in you code that sets the temperature.

**Comment by alexforencich** [comment]
What about set_temperature_setpoint?

**Comment by AnSem-Ellwood** [comment]
Having done some more reading, yes, this is probably what I am looking for.  Register 300 seems to be the right register. The function name is pretty cryptic, its basically the same name as the register that it writes to, which also has a cryptic name. I would have hoped for a higher level of abstraction. I will go ahead and test it.

**Comment by alexforencich** [comment]
Well, I would think it makes more sense to set the temp set point than the temperature directly, since you can't directly change the temperature.  Basically, you can read the temp and you can read or write the temp setpoint.  When you change the setpoint, the controller will try to drive the temp to the new set point.  If you want to add a bit of code does this at a higher level, then be my guest and send a patch or make a pull request.
